### PR TITLE
Some Changes

### PR DESCRIPTION
**Pull request by Paddyk45**
- Fix-ish a bug where the color of the logs changed after a print (idk how)
- You can set the log level with the enviroment variable LOG_LEVEL
- Make the server executable from any directory again again
- Changed the colors of DEBUG and ERROR log lines
- Probably some other stuff I can't remember

### CODE REVIEW

**Comment by Paddyk45** [comment]
Oh come on not this again

**Review by Juliandev02 — COMMENTED** [review]
image
Why did you change this? I have already removed the `Fore.` from all terminal colors.

**Comment by Paddyk45** [comment]
Oops, had an older version that didn't have the colors, will fix asap

**Comment by Juliandev02** [comment]
> Oops, had an older version that didn't have the colors, will fix asap

alright no problem

**Comment by Paddyk45** [comment]
done

**Comment by Paddyk45** [comment]
What do you mean with thag screenshot though

**Comment by Juliandev02** [comment]
> What do you mean with thag screenshot though

That the new color aliases have already been applied. Why the text "server started" was selected I do not know

**Review by Juliandev02 — APPROVED** [review]
This looks good to me and everything works.
Thanks for your contribution!

**Pull request merged**
