### PR TITLE
Rewrite logging

### LINKED ISSUE #4: Setting the username and sending a message allow bash commands to be executed in the server host
Using message:

Using username

### PR DESCRIPTION
**Pull request by Paddyk45**

### CODE REVIEW

**Comment by matteodev8** [comment]
@Paddyk45 Please resolve the conflict

**Comment by Paddyk45** [comment]
wtf where did that conflict come from

**Comment by matteodev8** [comment]
skill issue

**Review by Juliandev02 — CHANGES_REQUESTED** [review]
As @matteodev8 mentioned, please resolve the conflict. 
Also we already had planend to rewrite the logging system

**Comment by Paddyk45** [comment]
FINALLY FIXED IT

**Review by Juliandev02 — CHANGES_REQUESTED** [review]
So you basicially removed with the new logging the complete old logging via .txt files.
However, logging via text files is important for us, because this way we could only follow up if someone crashes the server or does something bad, for example. Your logging system limits this or removes it completely. Also, your logging system removes the ability to enable or disable certain logging.

**Comment by Paddyk45** [comment]
> So you basicially removed with the new logging the complete old logging via .txt files.
> However, logging via text files is important for us, because this way we could only follow up if someone crashes the server or does something bad, for example. Your logging system limits this or removes it completely. Also, your logging system removes the ability to enable or disable certain logging.

It still logs into logs.txt, but it logs into log.txt instead of log.txt and messages.txt

**Comment by Paddyk45** [comment]
And what do you mean with "certain logging"

**Comment by Juliandev02** [comment]
> And what do you mean with "certain logging"
Enable or disable certain logging, for example debug logging, message logging

**Comment by Juliandev02** [comment]
> > So you basicially removed with the new logging the complete old logging via .txt files.
> > However, logging via text files is important for us, because this way we could only follow up if someone crashes the server or does something bad, for example. Your logging system limits this or removes it completely. Also, your logging system removes the ability to enable or disable certain logging.
> 
> It still logs into a file, but it logs only into log.txt instead of log.txt and messages.txt

Okay. I had seen nothing when I looked over

**Comment by Paddyk45** [comment]
> > And what do you mean with "certain logging"
> Enable or disable certain logging, for example debug logging, message logging
That wasn't possible with print logging too?

**Comment by Paddyk45** [comment]
> > And what do you mean with "certain logging"
> Enable or disable certain logging, for example debug logging, message logging
That wasn't possible with print logging too?

**Comment by Juliandev02** [comment]
> > > And what do you mean with "certain logging"
> > 
> > 
> > Enable or disable certain logging, for example debug logging, message logging
> 
> That wasn't possible with print logging too?

You could disable Debug Logging and Message Logging in the main log of the server (not text files!!!)

**Review by Juliandev02 — APPROVED** [review]
Your rewrite of stbchat's logging system is "OKAY". I will definitely make some changes regarding logging, especially where NOT to log with the logger. 
Besides, why record the milliseconds in logging? 

Thank you for your contribution to Strawberry Chat.

**Comment by Juliandev02** [comment]
@matteodev8 please rewiew this in the next few hours

**Comment by Paddyk45** [comment]
> Besides, why record the milliseconds in logging?

The logging library does that for some reason, not like its annoying though

**Comment by Juliandev02** [comment]
> > Besides, why record the milliseconds in logging?
> 
> The logging library does that for some reason, not like its annoying though

I find it a bit cluttered and crowded

**Review by ghost — APPROVED** [review]
Looks fine to me, if it causes problems, `git revert` exists.

**Comment by Juliandev02** [comment]
👍 I'll merge it

**Pull request merged**
